=== hmrc/agent-client-authorisation/resources/public/api/conf/0.0/schemas/getclientinvitation.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "_links": {
      "type": "object",
      "properties": {
        "self": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          },
          "required": [
            "href"
          ]
        },
        "accept": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          },
          "required": [
            "href"
          ]
        },
        "reject": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          },
          "required": [
            "href"
          ]
        }
      },
      "required": [
        "self",
        "accept",
        "reject"
      ]
    },
    "created": {
      "type": "string"
    },
    "lastUpdated": {
      "type": "string"
    },
    "arn": {
      "type": "string"
    },
    "regime": {
      "type": "string"
    },
    "clientId": {
      "type": "string"
    },
    "status": {
      "type": "string"
    }
  },
  "required": [
    "_links",
    "created",
    "lastUpdated",
    "arn",
    "regime",
    "clientId",
    "status"
  ]
}

=== hmrc/agent-client-authorisation/resources/public/api/conf/0.0/examples/get-client-invitation-example.json
{
  "_links": {
    "self": {
      "href": "/clients/{clientId}/invitations/sent/f8068f15-95e0-45a3-b29a-10a078e3c707"
    },
    "accept": {
      "href": "/clients/{clientId}/invitations/sent/f8068f15-95e0-45a3-b29a-10a078e3c707/cancel"
    },
    "reject": {
      "href": "/clients/{clientId}/invitations/sent/f8068f15-95e0-45a3-b29a-10a078e3c707/cancel"
    }
  },
  "created": "2016-06-27T01:55:28+00.00",
  "lastUpdated": "2016-07-02T01:55:28+00.00",
  "arn": "123451234512345",
  "regime": "mtd-sa",
  "clientId": "123456789",
  "status": "pending"
}
